
*Hands-on of Big Data Analyst with TuV Certified Qualification*


---

# Artificial Neural Network

Artificial neural networks (ANN) or connectionist systems are computing systems that are inspired by, but not necessarily identical to, the biological neural networks that constitute animal brains. [*WIkipedia*](https://en.wikipedia.org/wiki/Artificial_neural_network). 

In this practice, we will keep working on the Telco Cutomer Churn Dataset.

In [36]:
# Import Library
import pandas as pd

In [37]:
#Import the files to Google Colab
url = 'https://raw.githubusercontent.com/rc-dbe/bigdatacertification/master/dataset/churn_trasnsformed_new.csv'
df_csv = pd.read_csv(url, sep=',',)

# Show 10 first Row
df_csv.head()

,Unnamed: 0,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,1,1,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,1,0,0,1,1,0,0,1,34,...,1,0,1,0,0,1,0,5695,18895.0,0
2,2,1,0,0,1,1,0,0,1,2,...,0,1,0,1,0,1,0,5385,10815.0,1
3,3,1,0,0,1,1,0,0,1,45,...,1,0,1,0,0,1,1,423,184075.0,0
4,4,0,1,0,1,1,0,0,1,2,...,0,1,0,1,0,0,1,707,15165.0,1

In [38]:
# Remove "Unnamed:O" Coloumn
df = df_csv.drop("Unnamed: 0", axis=1)
df.head()
# Data Frame for the output parameter 'Churn'
df_churn = df
# Data Frame for the output parameter 'Total Charges'
df_totalCharges = df

In [39]:
df_churn.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,0,1,0,1,1,0,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,0,0,1,1,0,0,1,34,1,...,1,0,1,0,0,1,0,5695,18895.0,0
2,1,0,0,1,1,0,0,1,2,1,...,0,1,0,1,0,1,0,5385,10815.0,1
3,1,0,0,1,1,0,0,1,45,0,...,1,0,1,0,0,1,1,423,184075.0,0
4,0,1,0,1,1,0,0,1,2,1,...,0,1,0,1,0,0,1,707,15165.0,1

In [40]:
df_totalCharges.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,0,1,0,1,1,0,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,0,0,1,1,0,0,1,34,1,...,1,0,1,0,0,1,0,5695,18895.0,0
2,1,0,0,1,1,0,0,1,2,1,...,0,1,0,1,0,1,0,5385,10815.0,1
3,1,0,0,1,1,0,0,1,45,0,...,1,0,1,0,0,1,1,423,184075.0,0
4,0,1,0,1,1,0,0,1,2,1,...,0,1,0,1,0,0,1,707,15165.0,1

In [41]:
# Check the Data Infomation
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender_0            7043 non-null   int64
 1   gender_1            7043 non-null   int64
 2   SeniorCitizen_0     7043 non-null   int64
 3   SeniorCitizen_1     7043 non-null   int64
 4   Partner_0           7043 non-null   int64
 5   Partner_1           7043 non-null   int64
 6   Dependents_0        7043 non-null   int64
 7   Dependents_1        7043 non-null   int64
 8   tenure              7043 non-null   int64
 9   PhoneService_0      7043 non-null   int64
 10  PhoneService_1      7043 non-null   int64
 11  MultipleLines_0     7043 non-null   int64
 12  MultipleLines_1     7043 non-null   int64
 13  MultipleLines_2     7043 non-null   int64
 14  InternetService_0   7043 non-null   int64
 15  InternetService_1   7043 non-null   int64
 16  InternetService_2   7043 non-null   int64
 17  OnlineSecurity_0    7043 non-null   int64
 18  OnlineSecurity_1    7043 non-null   int64
 19  OnlineSecurity_2    7043 non-null   int64
 20  OnlineBackup_0      7043 non-null   int64
 21  OnlineBackup_1      7043 non-null   int64
 22  OnlineBackup_2      7043 non-null   int64
 23  DeviceProtection_0  7043 non-null   int64
 24  DeviceProtection_1  7043 non-null   int64
 25  DeviceProtection_2  7043 non-null   int64
 26  TechSupport_0       7043 non-null   int64
 27  TechSupport_1       7043 non-null   int64
 28  TechSupport_2       7043 non-null   int64
 29  StreamingTV_0       7043 non-null   int64
 30  StreamingTV_1       7043 non-null   int64
 31  StreamingTV_2       7043 non-null   int64
 32  StreamingMovies_0   7043 non-null   int64
 33  StreamingMovies_1   7043 non-null   int64
 34  StreamingMovies_2   7043 non-null   int64
 35  Contract_0          7043 non-null   int64
 36  Contract_1          7043 non-null   int64
 37  Contract_2          7043 non-null   int64
 38  PaperlessBilling_0  7043 non-null   int64
 39  PaperlessBilling_1  7043 non-null   int64
 40  PaymentMethod_0     7043 non-null   int64
 41  PaymentMethod_1     7043 non-null   int64
 42  PaymentMethod_2     7043 non-null   int64
 43  MonthlyCharges      7043 non-null   int64
 44  TotalCharges        7043 non-null   float64
 45  Churn               7043 non-null   int64
dtypes: float64(1), int64(45)
memory usage: 2.5 MB

In [42]:
#Import MinMax Scaler
from sklearn.preprocessing import MinMaxScaler
#-------------------For 'Churn' as the output parameter-----------------------
# initialize min-max scaler
mm_scaler = MinMaxScaler()
column_names = df_churn.columns.tolist()
column_names.remove('Churn')

# Transform all attributes
df_churn[column_names] = mm_scaler.fit_transform(df_churn[column_names])
df_churn.sort_index(inplace=True)
df_churn.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420,0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766,0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449,1
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235,0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465,1

In [43]:
#-------------------For 'TotalCharges' as the output parameter------------------
column_names_2 = df_totalCharges.columns.tolist()
column_names_2.remove('TotalCharges')

# Transform all attributes
df_totalCharges[column_names_2] = mm_scaler.fit_transform(df_totalCharges[column_names_2])
df_totalCharges.sort_index(inplace=True)
df_totalCharges.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420,0.0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766,0.0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449,1.0
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465,1.0

In [44]:
# Selecting the Feature, by remove the unused feature 
feature = ['Churn']
train_feature_1 = df_churn.drop(feature, axis=1)

# Set The Target
train_target_1 = df_churn["Churn"]

In [45]:
# Show the Feature
train_feature_1.head(5)

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465

The scikit-learn library provides us with the splitter function 
train_test_split(). The original dataset is split into input(X) and output(Y) columns, then call the function passing both arrays and have them split into train and test subsets. Input(X) in this case is 'train_feature' and output(Y) will be 'train_target'. The size of the split is specified via the test_size argument, the value used in this case is 0.3 which denotes that 30 percent of the dataset will be allocated to the test set and 70 percent will be allocated to the training test. The shffle parameter is used to shuffle the data before splitting, its default value is 'True'.

In [47]:
# Split Data 
# For 70:30 train-test ratio
from sklearn.model_selection import train_test_split, cross_val_score
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(train_feature_1,
                                                            train_target_1, 
                                                            shuffle = True, 
                                                            test_size=0.3, 
                                                            random_state=1)

In [48]:
# Show the training data
X_train_1.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
5925,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.277778,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.056343,0.016308
4395,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.958333,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.875169,0.085848
1579,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.166667,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.676957,0.010935
1040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.194444,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.761302,0.014578
1074,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.013889,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.016194,0.000221

To train the ANN Model.We will use the MLPClassifier from Scikit Learn Library. The full documentation can be seen [HERE](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html). Below is the default parameter:

`sklearn.neural_network.MLPClassifier(hidden_layer_sizes=(100), activation=’relu’, solver=’adam’, alpha=0.0001, batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10)`

In [49]:
# Import Library
from sklearn.neural_network import MLPClassifier

# Fitting Model
mlp_1 = MLPClassifier(hidden_layer_sizes=(5), activation = 'relu', solver = 'adam',max_iter= 10000, verbose = True)
mlp_1 = mlp_1.fit(X_train_1,y_train_1)

# Prediction to Test Dataset
y_predmlp_1 = mlp_1.predict(X_test_1)

Iteration 1, loss = 0.79401292
Iteration 2, loss = 0.72210947
Iteration 3, loss = 0.67541786
Iteration 4, loss = 0.63262745
Iteration 5, loss = 0.59012190
Iteration 6, loss = 0.55399783
Iteration 7, loss = 0.52531226
Iteration 8, loss = 0.50369831
Iteration 9, loss = 0.48771327
Iteration 10, loss = 0.47599257
Iteration 11, loss = 0.46687038
Iteration 12, loss = 0.46053640
Iteration 13, loss = 0.45565785
Iteration 14, loss = 0.45158026
Iteration 15, loss = 0.44862926
Iteration 16, loss = 0.44608834
Iteration 17, loss = 0.44406494
Iteration 18, loss = 0.44245686
Iteration 19, loss = 0.44133263
Iteration 20, loss = 0.43990971
Iteration 21, loss = 0.43893884
Iteration 22, loss = 0.43798074
Iteration 23, loss = 0.43724869
Iteration 24, loss = 0.43679874
Iteration 25, loss = 0.43626712
Iteration 26, loss = 0.43566264
Iteration 27, loss = 0.43489068
Iteration 28, loss = 0.43429530
Iteration 29, loss = 0.43392866
Iteration 30, loss = 0.43380388
Iteration 31, loss = 0.43300306
Iteration 32, loss = 0.43273523
Iteration 33, loss = 0.43229403
Iteration 34, loss = 0.43201736
Iteration 35, loss = 0.43169257
Iteration 36, loss = 0.43139751
Iteration 37, loss = 0.43044613
Iteration 38, loss = 0.43001243
Iteration 39, loss = 0.42950161
Iteration 40, loss = 0.42913822
Iteration 41, loss = 0.42882940
Iteration 42, loss = 0.42846285
Iteration 43, loss = 0.42812386
Iteration 44, loss = 0.42775712
Iteration 45, loss = 0.42725543
Iteration 46, loss = 0.42712090
Iteration 47, loss = 0.42691197
Iteration 48, loss = 0.42661360
Iteration 49, loss = 0.42605265
Iteration 50, loss = 0.42574417
Iteration 51, loss = 0.42548836
Iteration 52, loss = 0.42557751
Iteration 53, loss = 0.42524325
Iteration 54, loss = 0.42476518
Iteration 55, loss = 0.42438643
Iteration 56, loss = 0.42426540
Iteration 57, loss = 0.42449513
Iteration 58, loss = 0.42375052
Iteration 59, loss = 0.42343310
Iteration 60, loss = 0.42322225
Iteration 61, loss = 0.42290799
Iteration 62, loss = 0.42246129
Iteration 63, loss = 0.42228770
Iteration 64, loss = 0.42172869
Iteration 65, loss = 0.42158106
Iteration 66, loss = 0.42137296
Iteration 67, loss = 0.42151535
Iteration 68, loss = 0.42106961
Iteration 69, loss = 0.42080065
Iteration 70, loss = 0.42060939
Iteration 71, loss = 0.42057333
Iteration 72, loss = 0.42024947
Iteration 73, loss = 0.41966085
Iteration 74, loss = 0.41962486
Iteration 75, loss = 0.41917800
Iteration 76, loss = 0.41934504
Iteration 77, loss = 0.41892843
Iteration 78, loss = 0.41862306
Iteration 79, loss = 0.41854294
Iteration 80, loss = 0.41812896
Iteration 81, loss = 0.41814856
Iteration 82, loss = 0.41772892
Iteration 83, loss = 0.41750721
Iteration 84, loss = 0.41729330
Iteration 85, loss = 0.41714338
Iteration 86, loss = 0.41728547
Iteration 87, loss = 0.41676819
Iteration 88, loss = 0.41669723
Iteration 89, loss = 0.41673603
Iteration 90, loss = 0.41655807
Iteration 91, loss = 0.41638347
Iteration 92, loss = 0.41622836
Iteration 93, loss = 0.41594107
Iteration 94, loss = 0.41584477
Iteration 95, loss = 0.41578680
Iteration 96, loss = 0.41571057
Iteration 97, loss = 0.41549389
Iteration 98, loss = 0.41523877
Iteration 99, loss = 0.41505846
Iteration 100, loss = 0.41529838
Iteration 101, loss = 0.41552150
Iteration 102, loss = 0.41519489
Iteration 103, loss = 0.41519807
Iteration 104, loss = 0.41487281
Iteration 105, loss = 0.41464982
Iteration 106, loss = 0.41432947
Iteration 107, loss = 0.41445925
Iteration 108, loss = 0.41477984
Iteration 109, loss = 0.41444946
Iteration 110, loss = 0.41419897
Iteration 111, loss = 0.41443835
Iteration 112, loss = 0.41426922
Iteration 113, loss = 0.41396278
Iteration 114, loss = 0.41407247
Iteration 115, loss = 0.41416375
Iteration 116, loss = 0.41383436
Iteration 117, loss = 0.41386571
Iteration 118, loss = 0.41376143
Iteration 119, loss = 0.41363203
Iteration 120, loss = 0.41366189
Iteration 121, loss = 0.41363076
Iteration 122, loss = 0.41361101
Iteration 123, loss = 0.41354706
Iteration 124, loss = 0.41325477
Iteration 125, loss = 0.41366904
Iteration 126, loss = 0.41406591
Iteration 127, loss = 0.41409411
Iteration 128, loss = 0.41369479
Iteration 129, loss = 0.41330155
Iteration 130, loss = 0.41334910
Iteration 131, loss = 0.41298169
Iteration 132, loss = 0.41289661
Iteration 133, loss = 0.41287054
Iteration 134, loss = 0.41287521
Iteration 135, loss = 0.41296764
Iteration 136, loss = 0.41306672
Iteration 137, loss = 0.41321944
Iteration 138, loss = 0.41277529
Iteration 139, loss = 0.41262397
Iteration 140, loss = 0.41277009
Iteration 141, loss = 0.41271265
Iteration 142, loss = 0.41268727
Iteration 143, loss = 0.41264723
Iteration 144, loss = 0.41261290
Iteration 145, loss = 0.41236093
Iteration 146, loss = 0.41257237
Iteration 147, loss = 0.41276598
Iteration 148, loss = 0.41320308
Iteration 149, loss = 0.41277846
Iteration 150, loss = 0.41249655
Iteration 151, loss = 0.41240397
Iteration 152, loss = 0.41234679
Iteration 153, loss = 0.41257545
Iteration 154, loss = 0.41249489
Iteration 155, loss = 0.41253523
Iteration 156, loss = 0.41208272
Iteration 157, loss = 0.41199610
Iteration 158, loss = 0.41224911
Iteration 159, loss = 0.41285207
Iteration 160, loss = 0.41206769
Iteration 161, loss = 0.41187137
Iteration 162, loss = 0.41218328
Iteration 163, loss = 0.41179415
Iteration 164, loss = 0.41178403
Iteration 165, loss = 0.41172516
Iteration 166, loss = 0.41184475
Iteration 167, loss = 0.41179266
Iteration 168, loss = 0.41225311
Iteration 169, loss = 0.41211319
Iteration 170, loss = 0.41206739
Iteration 171, loss = 0.41194528
Iteration 172, loss = 0.41156737
Iteration 173, loss = 0.41171784
Iteration 174, loss = 0.41142928
Iteration 175, loss = 0.41179986
Iteration 176, loss = 0.41226460
Iteration 177, loss = 0.41124158
Iteration 178, loss = 0.41175686
Iteration 179, loss = 0.41153723
Iteration 180, loss = 0.41148879
Iteration 181, loss = 0.41121086
Iteration 182, loss = 0.41153003
Iteration 183, loss = 0.41147948
Iteration 184, loss = 0.41135946
Iteration 185, loss = 0.41131025
Iteration 186, loss = 0.41136668
Iteration 187, loss = 0.41099539
Iteration 188, loss = 0.41129000
Iteration 189, loss = 0.41127847
Iteration 190, loss = 0.41108667
Iteration 191, loss = 0.41115161
Iteration 192, loss = 0.41165803
Iteration 193, loss = 0.41089083
Iteration 194, loss = 0.41227091
Iteration 195, loss = 0.41104914
Iteration 196, loss = 0.41084999
Iteration 197, loss = 0.41092593
Iteration 198, loss = 0.41093663
Iteration 199, loss = 0.41079163
Iteration 200, loss = 0.41075663
Iteration 201, loss = 0.41130640
Iteration 202, loss = 0.41101399
Iteration 203, loss = 0.41095611
Iteration 204, loss = 0.41126344
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [50]:
print('Number of Layer =', mlp_1.n_layers_)
print('Number of Iteration =', mlp_1.n_iter_)
print('Current loss computed with the loss function =', mlp_1.loss_)

Number of Layer = 3
Number of Iteration = 204
Current loss computed with the loss function = 0.41126343595011

Since it was the classification problem, we can evaluate the model using Confussion Matrix

A confusion matrix is a tabular summary of the number of correct and incorrect predictions made by a classifier. It can be used to evaluate the performance of a classification model through the calculation of performance metrics like accuracy, precision, recall and F-1 score.
y_test is a list that holds the actual labels. y_predmlp is a list that holds the predicted labels. metrics.confusion_matrix() takes in the list of actual labels and the list of predicted labels and calculates the confusion matrix for the given inputs.
The confusion matrix has four diferent values in an array, 'True Negative(Top-Left), 'False Positive'(Top-Right), 'False Negative'(Bottom-Left) and 'True Positive'(Bottom-Right).

In [51]:
# Import the metrics class
from sklearn import metrics


# Confussion Matrix
cnf_matrixmlp = metrics.confusion_matrix(y_test_1, y_predmlp_1)
cnf_matrixmlp

array([[1384,  201],
       [ 202,  326]])

In [55]:
# For 10:90 train-test ratio
from sklearn.model_selection import train_test_split, cross_val_score
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(train_feature_1,
                                                            train_target_1, 
                                                            shuffle = True, 
                                                            test_size=0.9, 
                                                            random_state=1)

In [56]:
# Show the training data
X_train_2.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
4342,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.722222,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.503205,0.357814
775,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.000000,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.931680,0.930030
4871,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.805556,1.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.061825,0.049571
4648,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.057692,0.000144
5209,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.000000,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.925776,0.090524

In [57]:
# Fitting Model
mlp_2 = MLPClassifier(hidden_layer_sizes=(5), activation = 'relu', solver = 'adam',max_iter= 10000, verbose = True)
mlp_2 = mlp_2.fit(X_train_2,y_train_2)

# Prediction to Test Dataset
y_predmlp_2 = mlp_2.predict(X_test_2)

Iteration 1, loss = 1.32477350
Iteration 2, loss = 1.22460246
Iteration 3, loss = 1.13016678
Iteration 4, loss = 1.04247656
Iteration 5, loss = 0.96365300
Iteration 6, loss = 0.89460088
Iteration 7, loss = 0.83301694
Iteration 8, loss = 0.77857534
Iteration 9, loss = 0.73287901
Iteration 10, loss = 0.69263110
Iteration 11, loss = 0.66162697
Iteration 12, loss = 0.63374532
Iteration 13, loss = 0.61188642
Iteration 14, loss = 0.59413189
Iteration 15, loss = 0.58071702
Iteration 16, loss = 0.56971832
Iteration 17, loss = 0.56133922
Iteration 18, loss = 0.55554444
Iteration 19, loss = 0.55080327
Iteration 20, loss = 0.54735671
Iteration 21, loss = 0.54418255
Iteration 22, loss = 0.54134750
Iteration 23, loss = 0.53904630
Iteration 24, loss = 0.53672534
Iteration 25, loss = 0.53469458
Iteration 26, loss = 0.53260272
Iteration 27, loss = 0.53055254
Iteration 28, loss = 0.52861042
Iteration 29, loss = 0.52672783
Iteration 30, loss = 0.52481907
Iteration 31, loss = 0.52305011
Iteration 32, loss = 0.52125612
Iteration 33, loss = 0.51954114
Iteration 34, loss = 0.51777458
Iteration 35, loss = 0.51619959
Iteration 36, loss = 0.51446021
Iteration 37, loss = 0.51297289
Iteration 38, loss = 0.51145983
Iteration 39, loss = 0.50986208
Iteration 40, loss = 0.50844856
Iteration 41, loss = 0.50695945
Iteration 42, loss = 0.50558051
Iteration 43, loss = 0.50414638
Iteration 44, loss = 0.50283363
Iteration 45, loss = 0.50152792
Iteration 46, loss = 0.50027286
Iteration 47, loss = 0.49893359
Iteration 48, loss = 0.49773988
Iteration 49, loss = 0.49658489
Iteration 50, loss = 0.49533803
Iteration 51, loss = 0.49426060
Iteration 52, loss = 0.49320446
Iteration 53, loss = 0.49213599
Iteration 54, loss = 0.49111646
Iteration 55, loss = 0.49012933
Iteration 56, loss = 0.48907045
Iteration 57, loss = 0.48808998
Iteration 58, loss = 0.48715018
Iteration 59, loss = 0.48628819
Iteration 60, loss = 0.48532159
Iteration 61, loss = 0.48443856
Iteration 62, loss = 0.48360348
Iteration 63, loss = 0.48270694
Iteration 64, loss = 0.48174988
Iteration 65, loss = 0.48096511
Iteration 66, loss = 0.48013679
Iteration 67, loss = 0.47919204
Iteration 68, loss = 0.47842740
Iteration 69, loss = 0.47770011
Iteration 70, loss = 0.47692930
Iteration 71, loss = 0.47628603
Iteration 72, loss = 0.47550368
Iteration 73, loss = 0.47484027
Iteration 74, loss = 0.47415769
Iteration 75, loss = 0.47347833
Iteration 76, loss = 0.47277081
Iteration 77, loss = 0.47218981
Iteration 78, loss = 0.47151313
Iteration 79, loss = 0.47085422
Iteration 80, loss = 0.47029058
Iteration 81, loss = 0.46968830
Iteration 82, loss = 0.46910754
Iteration 83, loss = 0.46847061
Iteration 84, loss = 0.46792005
Iteration 85, loss = 0.46736675
Iteration 86, loss = 0.46679836
Iteration 87, loss = 0.46627369
Iteration 88, loss = 0.46580613
Iteration 89, loss = 0.46537440
Iteration 90, loss = 0.46476675
Iteration 91, loss = 0.46426343
Iteration 92, loss = 0.46383813
Iteration 93, loss = 0.46335450
Iteration 94, loss = 0.46286315
Iteration 95, loss = 0.46239439
Iteration 96, loss = 0.46200103
Iteration 97, loss = 0.46154560
Iteration 98, loss = 0.46108266
Iteration 99, loss = 0.46054690
Iteration 100, loss = 0.46018061
Iteration 101, loss = 0.45973687
Iteration 102, loss = 0.45929069
Iteration 103, loss = 0.45884866
Iteration 104, loss = 0.45851598
Iteration 105, loss = 0.45807574
Iteration 106, loss = 0.45766428
Iteration 107, loss = 0.45733288
Iteration 108, loss = 0.45692998
Iteration 109, loss = 0.45674647
Iteration 110, loss = 0.45626087
Iteration 111, loss = 0.45594154
Iteration 112, loss = 0.45566615
Iteration 113, loss = 0.45534069
Iteration 114, loss = 0.45503048
Iteration 115, loss = 0.45475720
Iteration 116, loss = 0.45440824
Iteration 117, loss = 0.45411734
Iteration 118, loss = 0.45383344
Iteration 119, loss = 0.45353748
Iteration 120, loss = 0.45329747
Iteration 121, loss = 0.45296324
Iteration 122, loss = 0.45270836
Iteration 123, loss = 0.45245996
Iteration 124, loss = 0.45221932
Iteration 125, loss = 0.45200401
Iteration 126, loss = 0.45162258
Iteration 127, loss = 0.45137606
Iteration 128, loss = 0.45110680
Iteration 129, loss = 0.45086986
Iteration 130, loss = 0.45069009
Iteration 131, loss = 0.45041395
Iteration 132, loss = 0.45018164
Iteration 133, loss = 0.44994871
Iteration 134, loss = 0.44975371
Iteration 135, loss = 0.44951110
Iteration 136, loss = 0.44927796
Iteration 137, loss = 0.44915107
Iteration 138, loss = 0.44890015
Iteration 139, loss = 0.44868156
Iteration 140, loss = 0.44848885
Iteration 141, loss = 0.44827909
Iteration 142, loss = 0.44808365
Iteration 143, loss = 0.44789289
Iteration 144, loss = 0.44766287
Iteration 145, loss = 0.44746059
Iteration 146, loss = 0.44727990
Iteration 147, loss = 0.44711539
Iteration 148, loss = 0.44713996
Iteration 149, loss = 0.44672742
Iteration 150, loss = 0.44657529
Iteration 151, loss = 0.44638273
Iteration 152, loss = 0.44619137
Iteration 153, loss = 0.44600522
Iteration 154, loss = 0.44580798
Iteration 155, loss = 0.44567827
Iteration 156, loss = 0.44547092
Iteration 157, loss = 0.44531412
Iteration 158, loss = 0.44510620
Iteration 159, loss = 0.44500756
Iteration 160, loss = 0.44469457
Iteration 161, loss = 0.44453170
Iteration 162, loss = 0.44440245
Iteration 163, loss = 0.44425421
Iteration 164, loss = 0.44403590
Iteration 165, loss = 0.44385166
Iteration 166, loss = 0.44368242
Iteration 167, loss = 0.44347984
Iteration 168, loss = 0.44332400
Iteration 169, loss = 0.44315665
Iteration 170, loss = 0.44302305
Iteration 171, loss = 0.44292255
Iteration 172, loss = 0.44263843
Iteration 173, loss = 0.44248922
Iteration 174, loss = 0.44236792
Iteration 175, loss = 0.44216780
Iteration 176, loss = 0.44200565
Iteration 177, loss = 0.44185390
Iteration 178, loss = 0.44169267
Iteration 179, loss = 0.44151556
Iteration 180, loss = 0.44144451
Iteration 181, loss = 0.44121289
Iteration 182, loss = 0.44115701
Iteration 183, loss = 0.44098100
Iteration 184, loss = 0.44074198
Iteration 185, loss = 0.44064790
Iteration 186, loss = 0.44045228
Iteration 187, loss = 0.44045204
Iteration 188, loss = 0.44017419
Iteration 189, loss = 0.44014195
Iteration 190, loss = 0.43990837
Iteration 191, loss = 0.43975816
Iteration 192, loss = 0.43963489
Iteration 193, loss = 0.43948505
Iteration 194, loss = 0.43935644
Iteration 195, loss = 0.43925498
Iteration 196, loss = 0.43914117
Iteration 197, loss = 0.43897136
Iteration 198, loss = 0.43879973
Iteration 199, loss = 0.43863609
Iteration 200, loss = 0.43859527
Iteration 201, loss = 0.43839543
Iteration 202, loss = 0.43826500
Iteration 203, loss = 0.43810688
Iteration 204, loss = 0.43800754
Iteration 205, loss = 0.43790367
Iteration 206, loss = 0.43781341
Iteration 207, loss = 0.43776943
Iteration 208, loss = 0.43751139
Iteration 209, loss = 0.43734879
Iteration 210, loss = 0.43723624
Iteration 211, loss = 0.43711268
Iteration 212, loss = 0.43695004
Iteration 213, loss = 0.43683181
Iteration 214, loss = 0.43675037
Iteration 215, loss = 0.43664018
Iteration 216, loss = 0.43650106
Iteration 217, loss = 0.43633523
Iteration 218, loss = 0.43623578
Iteration 219, loss = 0.43612278
Iteration 220, loss = 0.43613133
Iteration 221, loss = 0.43587875
Iteration 222, loss = 0.43567727
Iteration 223, loss = 0.43553289
Iteration 224, loss = 0.43545472
Iteration 225, loss = 0.43533541
Iteration 226, loss = 0.43522513
Iteration 227, loss = 0.43508460
Iteration 228, loss = 0.43495999
Iteration 229, loss = 0.43484307
Iteration 230, loss = 0.43475824
Iteration 231, loss = 0.43459439
Iteration 232, loss = 0.43451287
Iteration 233, loss = 0.43434840
Iteration 234, loss = 0.43422207
Iteration 235, loss = 0.43420169
Iteration 236, loss = 0.43403602
Iteration 237, loss = 0.43387241
Iteration 238, loss = 0.43377017
Iteration 239, loss = 0.43363918
Iteration 240, loss = 0.43353445
Iteration 241, loss = 0.43339494
Iteration 242, loss = 0.43331315
Iteration 243, loss = 0.43315301
Iteration 244, loss = 0.43303853
Iteration 245, loss = 0.43291824
Iteration 246, loss = 0.43281005
Iteration 247, loss = 0.43273516
Iteration 248, loss = 0.43261091
Iteration 249, loss = 0.43251416
Iteration 250, loss = 0.43234983
Iteration 251, loss = 0.43220653
Iteration 252, loss = 0.43224118
Iteration 253, loss = 0.43195149
Iteration 254, loss = 0.43184307
Iteration 255, loss = 0.43170835
Iteration 256, loss = 0.43158858
Iteration 257, loss = 0.43149080
Iteration 258, loss = 0.43136471
Iteration 259, loss = 0.43119962
Iteration 260, loss = 0.43106101
Iteration 261, loss = 0.43096792
Iteration 262, loss = 0.43083688
Iteration 263, loss = 0.43073262
Iteration 264, loss = 0.43064202
Iteration 265, loss = 0.43057701
Iteration 266, loss = 0.43031327
Iteration 267, loss = 0.43028717
Iteration 268, loss = 0.43021906
Iteration 269, loss = 0.43007017
Iteration 270, loss = 0.43009837
Iteration 271, loss = 0.42978803
Iteration 272, loss = 0.42969601
Iteration 273, loss = 0.42952272
Iteration 274, loss = 0.42942102
Iteration 275, loss = 0.42925852
Iteration 276, loss = 0.42918817
Iteration 277, loss = 0.42921013
Iteration 278, loss = 0.42899857
Iteration 279, loss = 0.42887738
Iteration 280, loss = 0.42871536
Iteration 281, loss = 0.42859008
Iteration 282, loss = 0.42852549
Iteration 283, loss = 0.42841218
Iteration 284, loss = 0.42828258
Iteration 285, loss = 0.42812514
Iteration 286, loss = 0.42804934
Iteration 287, loss = 0.42788354
Iteration 288, loss = 0.42792355
Iteration 289, loss = 0.42767419
Iteration 290, loss = 0.42753589
Iteration 291, loss = 0.42739287
Iteration 292, loss = 0.42734480
Iteration 293, loss = 0.42723173
Iteration 294, loss = 0.42703801
Iteration 295, loss = 0.42691859
Iteration 296, loss = 0.42684282
Iteration 297, loss = 0.42677305
Iteration 298, loss = 0.42666449
Iteration 299, loss = 0.42649804
Iteration 300, loss = 0.42644822
Iteration 301, loss = 0.42628738
Iteration 302, loss = 0.42624869
Iteration 303, loss = 0.42597852
Iteration 304, loss = 0.42590003
Iteration 305, loss = 0.42569400
Iteration 306, loss = 0.42567135
Iteration 307, loss = 0.42545244
Iteration 308, loss = 0.42529947
Iteration 309, loss = 0.42516692
Iteration 310, loss = 0.42508662
Iteration 311, loss = 0.42496993
Iteration 312, loss = 0.42488448
Iteration 313, loss = 0.42469467
Iteration 314, loss = 0.42448657
Iteration 315, loss = 0.42431618
Iteration 316, loss = 0.42444817
Iteration 317, loss = 0.42425072
Iteration 318, loss = 0.42411770
Iteration 319, loss = 0.42389013
Iteration 320, loss = 0.42375004
Iteration 321, loss = 0.42361108
Iteration 322, loss = 0.42345790
Iteration 323, loss = 0.42334905
Iteration 324, loss = 0.42324006
Iteration 325, loss = 0.42307936
Iteration 326, loss = 0.42297258
Iteration 327, loss = 0.42289000
Iteration 328, loss = 0.42275015
Iteration 329, loss = 0.42256071
Iteration 330, loss = 0.42245959
Iteration 331, loss = 0.42237313
Iteration 332, loss = 0.42228085
Iteration 333, loss = 0.42213489
Iteration 334, loss = 0.42210473
Iteration 335, loss = 0.42184726
Iteration 336, loss = 0.42174641
Iteration 337, loss = 0.42158450
Iteration 338, loss = 0.42147357
Iteration 339, loss = 0.42133189
Iteration 340, loss = 0.42118977
Iteration 341, loss = 0.42114188
Iteration 342, loss = 0.42096116
Iteration 343, loss = 0.42081450
Iteration 344, loss = 0.42075790
Iteration 345, loss = 0.42074313
Iteration 346, loss = 0.42052581
Iteration 347, loss = 0.42039438
Iteration 348, loss = 0.42028333
Iteration 349, loss = 0.42016589
Iteration 350, loss = 0.42000252
Iteration 351, loss = 0.42000839
Iteration 352, loss = 0.41975709
Iteration 353, loss = 0.41973856
Iteration 354, loss = 0.41961286
Iteration 355, loss = 0.41941728
Iteration 356, loss = 0.41937451
Iteration 357, loss = 0.41914541
Iteration 358, loss = 0.41902584
Iteration 359, loss = 0.41919321
Iteration 360, loss = 0.41885940
Iteration 361, loss = 0.41867837
Iteration 362, loss = 0.41854589
Iteration 363, loss = 0.41830423
Iteration 364, loss = 0.41818737
Iteration 365, loss = 0.41817568
Iteration 366, loss = 0.41798335
Iteration 367, loss = 0.41780312
Iteration 368, loss = 0.41771605
Iteration 369, loss = 0.41752934
Iteration 370, loss = 0.41746071
Iteration 371, loss = 0.41726895
Iteration 372, loss = 0.41711516
Iteration 373, loss = 0.41695542
Iteration 374, loss = 0.41682775
Iteration 375, loss = 0.41666616
Iteration 376, loss = 0.41654808
Iteration 377, loss = 0.41642808
Iteration 378, loss = 0.41637109
Iteration 379, loss = 0.41621475
Iteration 380, loss = 0.41606120
Iteration 381, loss = 0.41592214
Iteration 382, loss = 0.41575727
Iteration 383, loss = 0.41566547
Iteration 384, loss = 0.41558828
Iteration 385, loss = 0.41539222
Iteration 386, loss = 0.41523785
Iteration 387, loss = 0.41511659
Iteration 388, loss = 0.41497436
Iteration 389, loss = 0.41487309
Iteration 390, loss = 0.41492494
Iteration 391, loss = 0.41464913
Iteration 392, loss = 0.41443102
Iteration 393, loss = 0.41435556
Iteration 394, loss = 0.41428768
Iteration 395, loss = 0.41418057
Iteration 396, loss = 0.41402874
Iteration 397, loss = 0.41415812
Iteration 398, loss = 0.41369167
Iteration 399, loss = 0.41358882
Iteration 400, loss = 0.41351468
Iteration 401, loss = 0.41345397
Iteration 402, loss = 0.41327344
Iteration 403, loss = 0.41325741
Iteration 404, loss = 0.41296701
Iteration 405, loss = 0.41289897
Iteration 406, loss = 0.41290940
Iteration 407, loss = 0.41266348
Iteration 408, loss = 0.41246207
Iteration 409, loss = 0.41270640
Iteration 410, loss = 0.41214762
Iteration 411, loss = 0.41217465
Iteration 412, loss = 0.41202787
Iteration 413, loss = 0.41188993
Iteration 414, loss = 0.41182289
Iteration 415, loss = 0.41163502
Iteration 416, loss = 0.41150533
Iteration 417, loss = 0.41138768
Iteration 418, loss = 0.41122196
Iteration 419, loss = 0.41114716
Iteration 420, loss = 0.41111955
Iteration 421, loss = 0.41103202
Iteration 422, loss = 0.41082500
Iteration 423, loss = 0.41067551
Iteration 424, loss = 0.41056271
Iteration 425, loss = 0.41058700
Iteration 426, loss = 0.41039823
Iteration 427, loss = 0.41031565
Iteration 428, loss = 0.41013915
Iteration 429, loss = 0.40995861
Iteration 430, loss = 0.40985295
Iteration 431, loss = 0.40979168
Iteration 432, loss = 0.40960556
Iteration 433, loss = 0.40944610
Iteration 434, loss = 0.40947655
Iteration 435, loss = 0.40924065
Iteration 436, loss = 0.40917135
Iteration 437, loss = 0.40897524
Iteration 438, loss = 0.40895768
Iteration 439, loss = 0.40884114
Iteration 440, loss = 0.40871031
Iteration 441, loss = 0.40846281
Iteration 442, loss = 0.40846120
Iteration 443, loss = 0.40841267
Iteration 444, loss = 0.40836555
Iteration 445, loss = 0.40813812
Iteration 446, loss = 0.40793761
Iteration 447, loss = 0.40777712
Iteration 448, loss = 0.40782372
Iteration 449, loss = 0.40771099
Iteration 450, loss = 0.40752551
Iteration 451, loss = 0.40731772
Iteration 452, loss = 0.40742003
Iteration 453, loss = 0.40708306
Iteration 454, loss = 0.40695558
Iteration 455, loss = 0.40682273
Iteration 456, loss = 0.40674541
Iteration 457, loss = 0.40657373
Iteration 458, loss = 0.40648740
Iteration 459, loss = 0.40637757
Iteration 460, loss = 0.40630670
Iteration 461, loss = 0.40625781
Iteration 462, loss = 0.40607490
Iteration 463, loss = 0.40610700
Iteration 464, loss = 0.40588761
Iteration 465, loss = 0.40566891
Iteration 466, loss = 0.40555024
Iteration 467, loss = 0.40546376
Iteration 468, loss = 0.40529686
Iteration 469, loss = 0.40520476
Iteration 470, loss = 0.40509339
Iteration 471, loss = 0.40512868
Iteration 472, loss = 0.40485410
Iteration 473, loss = 0.40478288
Iteration 474, loss = 0.40469193
Iteration 475, loss = 0.40467521
Iteration 476, loss = 0.40444222
Iteration 477, loss = 0.40433706
Iteration 478, loss = 0.40419267
Iteration 479, loss = 0.40413679
Iteration 480, loss = 0.40402772
Iteration 481, loss = 0.40388225
Iteration 482, loss = 0.40379816
Iteration 483, loss = 0.40375463
Iteration 484, loss = 0.40359604
Iteration 485, loss = 0.40353782
Iteration 486, loss = 0.40329714
Iteration 487, loss = 0.40314653
Iteration 488, loss = 0.40298267
Iteration 489, loss = 0.40284489
Iteration 490, loss = 0.40280227
Iteration 491, loss = 0.40267342
Iteration 492, loss = 0.40264219
Iteration 493, loss = 0.40244315
Iteration 494, loss = 0.40226822
Iteration 495, loss = 0.40219947
Iteration 496, loss = 0.40211943
Iteration 497, loss = 0.40193985
Iteration 498, loss = 0.40179291
Iteration 499, loss = 0.40171168
Iteration 500, loss = 0.40173619
Iteration 501, loss = 0.40145748
Iteration 502, loss = 0.40132438
Iteration 503, loss = 0.40124557
Iteration 504, loss = 0.40114407
Iteration 505, loss = 0.40106055
Iteration 506, loss = 0.40102861
Iteration 507, loss = 0.40106370
Iteration 508, loss = 0.40078980
Iteration 509, loss = 0.40055324
Iteration 510, loss = 0.40046092
Iteration 511, loss = 0.40035602
Iteration 512, loss = 0.40020821
Iteration 513, loss = 0.40012147
Iteration 514, loss = 0.39992850
Iteration 515, loss = 0.39978772
Iteration 516, loss = 0.39967241
Iteration 517, loss = 0.39963973
Iteration 518, loss = 0.39959280
Iteration 519, loss = 0.39945688
Iteration 520, loss = 0.39927746
Iteration 521, loss = 0.39922423
Iteration 522, loss = 0.39902696
Iteration 523, loss = 0.39900736
Iteration 524, loss = 0.39892053
Iteration 525, loss = 0.39880894
Iteration 526, loss = 0.39859849
Iteration 527, loss = 0.39851638
Iteration 528, loss = 0.39836798
Iteration 529, loss = 0.39833651
Iteration 530, loss = 0.39823893
Iteration 531, loss = 0.39804050
Iteration 532, loss = 0.39808799
Iteration 533, loss = 0.39790187
Iteration 534, loss = 0.39776862
Iteration 535, loss = 0.39762268
Iteration 536, loss = 0.39757588
Iteration 537, loss = 0.39748279
Iteration 538, loss = 0.39737430
Iteration 539, loss = 0.39723432
Iteration 540, loss = 0.39732345
Iteration 541, loss = 0.39710902
Iteration 542, loss = 0.39704628
Iteration 543, loss = 0.39687560
Iteration 544, loss = 0.39673515
Iteration 545, loss = 0.39670248
Iteration 546, loss = 0.39668800
Iteration 547, loss = 0.39652395
Iteration 548, loss = 0.39650925
Iteration 549, loss = 0.39629781
Iteration 550, loss = 0.39612147
Iteration 551, loss = 0.39600565
Iteration 552, loss = 0.39600964
Iteration 553, loss = 0.39589575
Iteration 554, loss = 0.39574824
Iteration 555, loss = 0.39559162
Iteration 556, loss = 0.39557922
Iteration 557, loss = 0.39540425
Iteration 558, loss = 0.39533981
Iteration 559, loss = 0.39535095
Iteration 560, loss = 0.39506919
Iteration 561, loss = 0.39493017
Iteration 562, loss = 0.39494060
Iteration 563, loss = 0.39484783
Iteration 564, loss = 0.39477617
Iteration 565, loss = 0.39464320
Iteration 566, loss = 0.39481191
Iteration 567, loss = 0.39459238
Iteration 568, loss = 0.39446111
Iteration 569, loss = 0.39426591
Iteration 570, loss = 0.39412966
Iteration 571, loss = 0.39400557
Iteration 572, loss = 0.39394040
Iteration 573, loss = 0.39382370
Iteration 574, loss = 0.39371299
Iteration 575, loss = 0.39375598
Iteration 576, loss = 0.39360788
Iteration 577, loss = 0.39348441
Iteration 578, loss = 0.39344886
Iteration 579, loss = 0.39324801
Iteration 580, loss = 0.39333950
Iteration 581, loss = 0.39324227
Iteration 582, loss = 0.39302921
Iteration 583, loss = 0.39302134
Iteration 584, loss = 0.39301190
Iteration 585, loss = 0.39284893
Iteration 586, loss = 0.39262044
Iteration 587, loss = 0.39258180
Iteration 588, loss = 0.39246709
Iteration 589, loss = 0.39234169
Iteration 590, loss = 0.39222667
Iteration 591, loss = 0.39213244
Iteration 592, loss = 0.39219954
Iteration 593, loss = 0.39195576
Iteration 594, loss = 0.39188880
Iteration 595, loss = 0.39201034
Iteration 596, loss = 0.39178749
Iteration 597, loss = 0.39178393
Iteration 598, loss = 0.39186113
Iteration 599, loss = 0.39167370
Iteration 600, loss = 0.39139540
Iteration 601, loss = 0.39134844
Iteration 602, loss = 0.39128345
Iteration 603, loss = 0.39122164
Iteration 604, loss = 0.39098810
Iteration 605, loss = 0.39104568
Iteration 606, loss = 0.39089356
Iteration 607, loss = 0.39094332
Iteration 608, loss = 0.39074359
Iteration 609, loss = 0.39072458

Accuracy measures how often the model is correct.

It is calculated as: Accuracy = (TP + TN)/Total Predictions

Precision means of the positives predicted, what percentage is truly positive?

It is calculated as: Precision = TP/(TP + FP)

Recall indicates of all the positive cases, what percentage are predicted positive?

Recall = TP/(TP + FN)

F1 Score is the harmonic mean of precision and recall.

F1 Score = 2(PrceisionRecall)/(Precision + Recall)

In [58]:
###############################################################################
# 2. Train only 10% of the dataset, then run cell by cell from the top again. 
#    Compare the performance and explain. 

# Show the Accuracy, Precision, Recall, F1, etc. 
acc_mlp_1   = metrics.accuracy_score(y_test_1, y_predmlp_1)
prec_mlp_1  = metrics.precision_score(y_test_1, y_predmlp_1)
rec_mlp_1   = metrics.recall_score(y_test_1, y_predmlp_1)
f1_mlp_1    = metrics.f1_score(y_test_1, y_predmlp_1)
kappa_mlp_1 = metrics.cohen_kappa_score(y_test_1, y_predmlp_1)

acc_mlp_2   = metrics.accuracy_score(y_test_2, y_predmlp_2)
prec_mlp_2  = metrics.precision_score(y_test_2, y_predmlp_2)
rec_mlp_2   = metrics.recall_score(y_test_2, y_predmlp_2)
f1_mlp_2    = metrics.f1_score(y_test_2, y_predmlp_2)
kappa_mlp_2 = metrics.cohen_kappa_score(y_test_2, y_predmlp_2)

print("-------------Performance with 70:30 train-test ratio-------------------")
print("Accuracy:", acc_mlp_1)
print("Precision:", prec_mlp_1)
print("Recall:", rec_mlp_1)
print("F1 Score:", f1_mlp_1)
print("Cohens Kappa Score:", kappa_mlp_1)

print("-------------Performance with 10:90 train-test ratio-------------------")
print("Accuracy:", acc_mlp_2)
print("Precision:", prec_mlp_2)
print("Recall:", rec_mlp_2)
print("F1 Score:", f1_mlp_2)
print("Cohens Kappa Score:", kappa_mlp_2)

-------------Performance with 70:30 train-test ratio-------------------
Accuracy: 0.8092759110269758
Precision: 0.618595825426945
Recall: 0.6174242424242424
F1 Score: 0.6180094786729858
Cohens Kappa Score: 0.4909203845512323
-------------Performance with 10:90 train-test ratio-------------------
Accuracy: 0.7777251932481464
Precision: 0.5798004987531172
Recall: 0.5585585585585585
F1 Score: 0.5689813398592842
Cohens Kappa Score: 0.4193013516594737

It is clearly seen that the model's correctness and the true performance is dropped moderately when the training data size is reduced.
This is because with the 70:30 train-test ratio, the model has enough data to trian the model, before testing it on the unknown test data as compared to the 10:90 train test ratio, where in contrast the model has huge amount of unknown data.

In [60]:
#####################################################################
# 3. Change the output parameter from Churn to TotalCharges, and run again to find 
#    out the mean squared error (MSE) value. (hint: use Multi Regressor)
# Selecting the Feature, by remove the unused feature 
feature_2 = ['TotalCharges']
train_feature_2 = df_churn.drop(feature_2, axis=1)

# Set The Target
train_target_2 = df_churn["TotalCharges"]

In [62]:
train_feature_2.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,Churn
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,1.0
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,1.0

In [63]:
# Split Data 
from sklearn.model_selection import train_test_split, cross_val_score
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(train_feature_2,
                                                            train_target_2, 
                                                            shuffle = True, 
                                                            test_size=0.3, 
                                                            random_state=1)

In [64]:
X_train_3.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,Churn
5925,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.277778,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.056343,0.0
4395,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.958333,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.875169,1.0
1579,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.166667,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.676957,1.0
1040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.194444,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.761302,1.0
1074,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.013889,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.016194,0.0

In [67]:
# Import Library
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Fitting Model

mlp = MLPRegressor(hidden_layer_sizes=(5), activation = 'relu', solver = 'adam',max_iter= 10000, verbose = True)
mlp = mlp.fit(X_train_3,y_train_3)

# Prediction to Test Dataset
y_predmlp_3 = mlp.predict(X_test_3)

Iteration 1, loss = 0.12300890
Iteration 2, loss = 0.07460380
Iteration 3, loss = 0.05837719
Iteration 4, loss = 0.04732886
Iteration 5, loss = 0.03947946
Iteration 6, loss = 0.03386506
Iteration 7, loss = 0.02952799
Iteration 8, loss = 0.02622240
Iteration 9, loss = 0.02363127
Iteration 10, loss = 0.02162410
Iteration 11, loss = 0.02009372
Iteration 12, loss = 0.01883709
Iteration 13, loss = 0.01784293
Iteration 14, loss = 0.01701259
Iteration 15, loss = 0.01639582
Iteration 16, loss = 0.01588724
Iteration 17, loss = 0.01559070
Iteration 18, loss = 0.01536974
Iteration 19, loss = 0.01521394
Iteration 20, loss = 0.01511684
Iteration 21, loss = 0.01504173
Iteration 22, loss = 0.01500881
Iteration 23, loss = 0.01493504
Iteration 24, loss = 0.01490759
Iteration 25, loss = 0.01486707
Iteration 26, loss = 0.01488627
Iteration 27, loss = 0.01488261
Iteration 28, loss = 0.01481902
Iteration 29, loss = 0.01480451
Iteration 30, loss = 0.01479979
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [68]:
# Mean Squared Error
mse = mean_squared_error(y_test_3, y_predmlp_3)
print("The mean squared error (MSE) on test set: {:.4f}".format(mse))

The mean squared error (MSE) on test set: 0.0301